background            #3a3c3e
foreground            #d9eed2
cursor                #72ffb5
selection_background  #2a9b34
color0                #72ffb5
color8                #72ffb5
color1                #fb0029
color9                #a6ff3e
color2                #72ffb5
color10               #9fff6d
color3                #649a25
color11               #72ffb5
color4                #6dd5a2
color12               #72ffb5
color5                #72ffb5
color13               #50ff3d
color6                #1dbc60
color14               #22ff71
color7                #dffeee
color15               #daeed0
selection_foreground  #72ffb5

# color 4 is normal text
# color 6 is completion 
