preload = /home/allan/Downloads/images/library.jpg
wallpaper = eDP-1, /home/allan/Downloads/images/library.jpg
wallpaper = HDMI-A-1, /home/allan/Downloads/images/library.jpg
wallpaper = DP-1, /home/allan/Downloads/images/library.jpg

#preload = /home/allan/Downloads/images/aquarium_reformat.jpg
#wallpaper = eDP-1, /home/allan/Downloads/images/aquarium_reformat.jpg
#wallpaper = HDMI-A-1, /home/allan/Downloads/images/aquarium_reformat.jpg
#wallpaper = DP-1, /home/allan/Downloads/images/aquarium_reformat.jpg
